// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAbJ6E4wejk-7IjJT90zl1XLsbTgi1RX0',
    appId: '1:673529712984:web:3dda807526ea69484ed52d',
    messagingSenderId: '673529712984',
    projectId: 'messease-e73d4',
    authDomain: 'messease-e73d4.firebaseapp.com',
    storageBucket: 'messease-e73d4.firebasestorage.app',
    measurementId: 'G-40VY0CMCDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjJzJxOEB6dJajXqVbC-KwJtsH56A_3nc',
    appId: '1:673529712984:android:9f12bd7e1d65af2c4ed52d',
    messagingSenderId: '673529712984',
    projectId: 'messease-e73d4',
    storageBucket: 'messease-e73d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWWwk3JeqHpjKwopUzvEKDFvT8ZyyTxz8',
    appId: '1:673529712984:ios:5d1a0203882299ea4ed52d',
    messagingSenderId: '673529712984',
    projectId: 'messease-e73d4',
    storageBucket: 'messease-e73d4.firebasestorage.app',
    iosBundleId: 'com.example.messease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWWwk3JeqHpjKwopUzvEKDFvT8ZyyTxz8',
    appId: '1:673529712984:ios:5d1a0203882299ea4ed52d',
    messagingSenderId: '673529712984',
    projectId: 'messease-e73d4',
    storageBucket: 'messease-e73d4.firebasestorage.app',
    iosBundleId: 'com.example.messease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAbJ6E4wejk-7IjJT90zl1XLsbTgi1RX0',
    appId: '1:673529712984:web:bb3bc934712a35b64ed52d',
    messagingSenderId: '673529712984',
    projectId: 'messease-e73d4',
    authDomain: 'messease-e73d4.firebaseapp.com',
    storageBucket: 'messease-e73d4.firebasestorage.app',
    measurementId: 'G-XXJ7RKG8EL',
  );
}
